server:
  port: 8080
#  servlet:
#    context-path: /api
spring:
  application:
    name: petz-api
  cloud:
    config:
      name:
      uri:
  profiles:
    active: develop

---
spring:
  profiles: develop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      default_schema: sc_petz
      ddl-auto: none
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false



logging:
  level:
    br: TRACE

---
spring:
  profiles: local

server:
  port: 8081